#!/usr/bin/env python
"""Manuscript figures for the chr2 inversion (sec 3a-3d, 3o).

    .venv/bin/python -m illex.scripts.figures_inversion

WHY THIS EXISTS
---------------
Every msinv modelling result in the manuscript existed only as text and CSV.
The descriptive inversion work (karyotype PCA, LD, cline) has figures under
``analysis/steps/``; the model -- which is what section 3 is built on -- had
none. These three cover the load-bearing claims:

  fig1  the object          differentiation along chr2, the pinned breakpoints,
                            and the per-arrangement diversity that motivates
                            the whole decline model
  fig2  the fitted history  p(t), and the two chi-square profiles that bound
                            it -- including the t_fall profile that excludes
                            the neutral drift-out arm
  fig3  the barrier         the AA/BB joint SFS against its collinear control

NOTHING IS RECOMPUTED HERE. Every number is read from ``results/illex/`` or
``.tmp/sfs2d/`` and, where a score is needed, recomputed from the same stored
per-cell simulation output with the same weighted chi-square the fit used.
The one exception is the trajectory itself, which is regenerated by calling
``illex.balancing.decline_curve`` at the fitted parameters -- the same
function ``build_decline_sim`` calls -- so the drawn curve IS the fitted one
rather than a sketch of it.

THE WEIGHTED SCORE
------------------
``refit_decline*.csv`` stores an UNWEIGHTED ``score`` column, which is what
the fit reported before the f1 target acquired a standard error. Once all
three targets had SEs the fit moved to a weighted chi-square, so the stored
column is stale and is NOT used. ``chi2()`` below recomputes it from the three
stored ratios against TARGETS. This reproduces the manuscript profile exactly
(t_fall: 0.85 / 0 / 0.74 / 8.36 / 81.52; t_decline at 0: 35.45).
"""
from __future__ import annotations

import csv
import json
from pathlib import Path

import matplotlib as mpl
mpl.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.gridspec import GridSpec

from illex.balancing import decline_curve
from illex.theory import N_growth

R = Path("results/illex")
# The realSFS 2D matrices were produced in .tmp/ (see NOTES sec 8.22) and are
# copied into results/ so fig3 survives a scratch clean; .tmp/ is the fallback.
SFS2D = Path("results/illex/sfs2d")
TMP = SFS2D if (SFS2D / "AA_BB.body.2dSFS").exists() else Path(".tmp/sfs2d")
OUT = R / "figures"

# --- pinned breakpoints (NOTES sec 8.31, manuscript sec 3o) ---------------
BP_L, BP_R = 60_540_000, 79_500_000
CHR2_LEN = 119_466_599
CONTROL = (10_000_000, 30_000_000)      # the collinear control, sec 8.19

# --- fitted point (weighted chi-square best cell) ------------------------
FIT = dict(t_inv=850_000.0, p_hist=0.74, t_decline=175_000.0,
           t_fall=100_000.0, p_now=0.374)

# --- empirical targets and their block-jackknife SEs ---------------------
TARGETS = {"pi_i_over_pi_s": (1.3556, 0.0481),
           "dxy_over_pi_i":  (1.3848, 0.0214),
           "f1_ratio":       (0.8125, 0.0076)}

# AA = ancestral/collinear, BB = derived/inverted.
C_AA, C_BB, C_DXY = "#2c6fbb", "#d1495b", "#3f3f46"
C_INV, C_CTRL = "#d1495b", "#2c6fbb"

plt.rcParams.update({
    "font.size": 8, "axes.labelsize": 8, "axes.titlesize": 8.5,
    "xtick.labelsize": 7, "ytick.labelsize": 7, "legend.fontsize": 7,
    "axes.spines.top": False, "axes.spines.right": False,
    "axes.linewidth": 0.7, "xtick.major.width": 0.7,
    "ytick.major.width": 0.7, "figure.dpi": 150,
})


def chi2(row) -> float:
    """Weighted chi-square of one simulated cell against the three targets."""
    return sum(((float(row[k]) - t) / se) ** 2
               for k, (t, se) in TARGETS.items())


def profile(tag: str, key: str):
    """(values, delta-chi2, best-rows) profiling `key`, others re-optimised."""
    rows = list(csv.DictReader(open(R / f"refit_decline{tag}.csv")))
    best: dict[float, tuple[float, dict]] = {}
    for r in rows:
        v, c = float(r[key]), chi2(r)
        if v not in best or c < best[v][0]:
            best[v] = (c, r)
    gmin = min(c for c, _ in best.values())
    vals = sorted(best)
    return (np.array(vals),
            np.array([best[v][0] - gmin for v in vals]),
            [best[v][1] for v in vals])


def load_csv(path, **cast):
    rows = list(csv.DictReader(open(path)))
    return {k: np.array([f(r[k]) for r in rows]) for k, f in cast.items()}


def save(fig, name):
    OUT.mkdir(parents=True, exist_ok=True)
    for ext in ("png", "pdf"):
        fig.savefig(OUT / f"{name}.{ext}", dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {OUT}/{name}.{{png,pdf}}")


# =========================================================================
# FIGURE 1 -- the object
# =========================================================================
def figure1():
    # (a) genome scan restricted to chr2. The scan is AA-vs-BB Fst at 100 kb;
    #     chrom '2' is chr2 (verified: 1,194 windows out to 119.3 Mb, and the
    #     high-Fst windows at 60-80 Mb fall on it).
    fs = [r for r in csv.DictReader(open(R / "karyotype_fst_scan.tsv"),
                                    delimiter="\t") if r["chrom"] == "2"]
    fw = np.array([float(r["win"]) for r in fs])
    ff = np.array([float(r["fst"]) for r in fs])
    o = np.argsort(fw)
    fw, ff = fw[o] / 1e6 + 0.05, ff[o]

    # (b) per-arrangement diversity at 100 kb over 60-80 Mb. The chrom column
    #     in this file is a within-query index, not a chromosome name -- the
    #     region loaded was 2:60,000,000-80,000,000 (empirical_jackknife.py).
    d = load_csv(R / "empirical_jackknife_windows.csv",
                 window_start=float, pi_AA=float, pi_BB=float, dxy=float)
    o = np.argsort(d["window_start"])
    mid = d["window_start"][o] / 1e6 + 0.05
    pAA, pBB, dxy = d["pi_AA"][o], d["pi_BB"][o], d["dxy"][o]

    fig = plt.figure(figsize=(7.1, 7.3))
    gs = GridSpec(3, 2, height_ratios=[1.0, 1.25, 0.9], hspace=0.62,
                  wspace=0.20, figure=fig)

    # ---- (a) chr2-wide differentiation ---------------------------------
    ax = fig.add_subplot(gs[0, :])
    ax.axvspan(BP_L / 1e6, BP_R / 1e6, color=C_INV, alpha=0.10, lw=0)
    ax.axvspan(CONTROL[0] / 1e6, CONTROL[1] / 1e6, color=C_CTRL,
               alpha=0.10, lw=0)
    ax.plot(fw, ff, lw=0.5, color="#3f3f46")
    for b in (BP_L, BP_R):
        ax.axvline(b / 1e6, color=C_INV, lw=0.9, ls="--")
    ax.set_xlim(0, CHR2_LEN / 1e6)
    ax.set_ylim(0, 0.86)
    ax.set_yticks([0, 0.2, 0.4, 0.6])
    ax.set_ylabel("$F_{ST}$  (AA vs BB)")
    ax.set_xlabel("chr2 position (Mb)", labelpad=1.5)
    ax.set_title("a   The inversion is the only differentiated region on chr2",
                 loc="left", fontweight="bold", pad=5)
    ax.text((BP_L + BP_R) / 2e6, 0.83, "inversion\n60.54–79.50 Mb",
            ha="center", va="top", fontsize=6.8, color=C_INV, linespacing=1.25)
    ax.text(sum(CONTROL) / 2e6, 0.83, "collinear\ncontrol", ha="center",
            va="top", fontsize=6.8, color=C_CTRL, linespacing=1.25)
    # the 32-58 Mb stretch is the only part of the panel with no data in it
    ax.text(0.325, 0.70, "median $F_{ST}$\ninversion 0.396  ·  collinear 0.014",
            transform=ax.transAxes, ha="center", va="center", fontsize=6.5,
            color="#71717a", linespacing=1.4)

    # ---- (b) per-arrangement diversity ---------------------------------
    ax = fig.add_subplot(gs[1, :])
    ax.axvspan(BP_L / 1e6, BP_R / 1e6, color=C_INV, alpha=0.07, lw=0)
    ax.plot(mid, dxy * 1e3, lw=0.8, color=C_DXY, label=r"$d_{xy}$ (AA, BB)")
    ax.plot(mid, pBB * 1e3, lw=0.8, color=C_BB,
            label=r"$\pi_{BB}$  inverted, derived")
    ax.plot(mid, pAA * 1e3, lw=0.8, color=C_AA, label=r"$\pi_{AA}$  ancestral")
    for b in (BP_L, BP_R):
        ax.axvline(b / 1e6, color=C_INV, lw=0.9, ls="--")
    ax.set_xlim(60, 80)
    ax.set_ylim(0, 6.4)
    ax.set_yticks([0, 1, 2, 3, 4])
    ax.set_xlabel("chr2 position (Mb)", labelpad=1.5)
    ax.set_ylabel(r"diversity  ($\times 10^{-3}$)")
    ax.legend(loc="upper left", ncol=3, frameon=False, borderaxespad=0.0,
              bbox_to_anchor=(0.0, 1.005), columnspacing=1.5, handlelength=1.7,
              handletextpad=0.5)
    ax.set_title("b   The inverted arrangement is the MORE diverse one — "
                 "it was formerly commoner",
                 loc="left", fontweight="bold", pad=5)
    ax.text(0.5, 0.845,
            r"$\pi_I/\pi_S = 1.356 \pm 0.048$      "
            r"equilibrium at $p = 0.374$ predicts $0.597$      "
            r"$d_{xy}/\pi_I = 1.385 \pm 0.021$",
            transform=ax.transAxes, ha="center", va="center", fontsize=6.8,
            color="#3f3f46")

    # ---- (c, d) breakpoint zooms ---------------------------------------
    for j, (bp, lab) in enumerate(((BP_L, "left"), (BP_R, "right"))):
        ax = fig.add_subplot(gs[2, j])
        lo, hi = bp - 2.5e6, bp + 2.5e6
        m = (fw >= lo / 1e6) & (fw <= hi / 1e6)
        ax.axvspan(*((bp / 1e6, hi / 1e6) if j == 0 else (lo / 1e6, bp / 1e6)),
                   color=C_INV, alpha=0.07, lw=0)
        ax.plot(fw[m], ff[m], lw=0.7, color="#3f3f46", marker="o", ms=1.9,
                mfc="#3f3f46", mec="none")
        ax.axvline(bp / 1e6, color=C_INV, lw=1.0, ls="--")
        ax.set_xlim(lo / 1e6, hi / 1e6)
        ax.set_ylim(0, 0.78)
        ax.set_yticks([0, 0.2, 0.4, 0.6])
        ax.set_xlabel("chr2 position (Mb)", labelpad=1.5)
        if j == 0:
            ax.set_ylabel("$F_{ST}$")
        ax.set_title(f"{'cd'[j]}   {lab} breakpoint — {bp / 1e6:.2f} Mb",
                     loc="left", fontweight="bold", pad=5)
        # keep the label on the low-Fst flank, away from the step itself
        ax.text(0.04 if j == 0 else 0.96, 0.955, "a step, not a ramp",
                transform=ax.transAxes, ha="left" if j == 0 else "right",
                va="top", fontsize=6.5, color="#71717a")

    save(fig, "fig1_inversion_object")


# =========================================================================
# FIGURE 2 -- the fitted history
# =========================================================================
def drift_sd(p0: float, t_lo: float, t_hi: float, n: int = 20000) -> float:
    """SD of a neutral frequency change over the backward window [t_lo, t_hi].

    Var[p(t) - p0] = p0(1-p0) * INT dt / (2 N(t)) under the fitted growth
    demography. Same expression as illex.scripts.neutrality_check.
    """
    t = np.linspace(t_lo, t_hi, n)
    return float(np.sqrt(p0 * (1.0 - p0)
                         * np.trapezoid(1.0 / (2.0 * N_growth(t)), t)))


def figure2():
    times, freqs, s_fall = decline_curve(
        t_inv=FIT["t_inv"], t_decline=FIT["t_decline"],
        t_fall=FIT["t_fall"], p_hist=FIT["p_hist"], p_now=FIT["p_now"])
    times, freqs = np.asarray(times) / 1e3, np.asarray(freqs)

    fig = plt.figure(figsize=(7.1, 5.6))
    gs = GridSpec(2, 2, height_ratios=[1.3, 1.0], hspace=0.60, wspace=0.24,
                  figure=fig)

    # ---- (a) the fitted trajectory -------------------------------------
    ax = fig.add_subplot(gs[0, :])

    # Neutral drift envelope, released from p_hist at the START of the fall
    # (t = t_decline + t_fall) and run forward to the present. This is the
    # comparison the drift-out hypothesis needs: it never reaches 0.374.
    t0 = FIT["t_decline"] + FIT["t_fall"]
    tb = np.linspace(0.0, t0, 400)
    sd = np.array([drift_sd(FIT["p_hist"], t, t0) for t in tb])
    for k in (2, 1):
        ax.fill_between(tb / 1e3, np.clip(FIT["p_hist"] - k * sd, 0, 1),
                        np.clip(FIT["p_hist"] + k * sd, 0, 1),
                        color="#71717a", alpha=0.13, lw=0, zorder=1)
    ax.plot(tb / 1e3, np.full_like(tb, FIT["p_hist"]), lw=0.7, ls=":",
            color="#71717a", zorder=1)

    ax.axhline(FIT["p_now"], lw=0.7, ls="--", color="#52525b", zorder=2)
    ax.plot(times, freqs, lw=1.9, color=C_BB, zorder=3, solid_capstyle="round")
    ax.scatter([0], [FIT["p_now"]], s=28, color=C_BB, zorder=4,
               edgecolor="white", linewidth=0.9)

    ax.set_xlim(FIT["t_inv"] / 1e3 * 1.06, -14)
    ax.set_ylim(0, 0.96)
    ax.set_yticks([0, 0.2, 0.374, 0.6, 0.74, 0.9])
    ax.set_yticklabels(["0", "0.2", "0.374", "0.6", "0.74", "0.9"])
    ax.set_xlabel("time before present (ka)", labelpad=1.5)
    ax.set_ylabel("frequency of the\ninverted (BB) arrangement", labelpad=2,
                  linespacing=1.3)
    ax.set_title("a   The fitted trajectory — and why the fall cannot be drift",
                 loc="left", fontweight="bold", pad=5)

    ax.annotate("arose ~850 ka", xy=(FIT["t_inv"] / 1e3, FIT["p_hist"]),
                xytext=(FIT["t_inv"] / 1e3 - 8, 0.90), fontsize=7,
                color="#3f3f46", ha="left", va="center",
                arrowprops=dict(arrowstyle="-", lw=0.6, color="#71717a",
                                shrinkA=1, shrinkB=3))
    ax.text(530, 0.785, "held near $p \\approx 0.74$ for ~575 ky", fontsize=7,
            color="#3f3f46", ha="center")
    ax.annotate("the fall\n275 → 175 ka\n$N_e s \\approx 475$",
                xy=(258, 0.60), xytext=(170, 0.63), fontsize=7, color=C_BB,
                ha="center", va="center", linespacing=1.35,
                arrowprops=dict(arrowstyle="->", lw=0.7, color=C_BB,
                                shrinkA=3, shrinkB=3,
                                connectionstyle="arc3,rad=-0.15"))
    ax.text(-8, FIT["p_now"] + 0.035, "$p = 0.374$ today", fontsize=7,
            color="#3f3f46", ha="right", va="bottom")
    ax.text(118, 0.115,
            "grey band: ±1, ±2 SD of pure drift released from $p_{hist}$\n"
            "drift needs 514 ky (2σ) to produce a fall this large",
            fontsize=6.5, color="#52525b", ha="center", va="center",
            linespacing=1.4)

    # ---- (b, c) the two profiles ---------------------------------------
    for j, (tag, key, title, xlab, note, npos) in enumerate((
            ("tdecline", "t_decline", "b   When the fall ended",
             "$t_{decline}$  (ka)",
             "the fall is over —\n“ending now” rejected", (0.97, 0.62)),
            ("tfall2", "t_fall", "c   How long the fall took",
             "$t_{fall}$  (ky)",
             "neutral drift-out\narm excluded", (0.03, 0.93)))):
        ax = fig.add_subplot(gs[1, j])
        v, dc, _ = profile(tag, key)
        ax.axhspan(0, 2, color="#22c55e", alpha=0.09, lw=0)
        ax.axhline(2, lw=0.7, ls=":", color="#52525b")
        ax.plot(v / 1e3, dc, marker="o", ms=3.4, lw=1.1, color=C_BB,
                mfc="white", mec=C_BB, mew=1.1, clip_on=False, zorder=3)
        ax.set_yscale("symlog", linthresh=2)
        ax.set_ylim(-0.4, 260)
        ax.set_yticks([0, 1, 2, 10, 100])
        ax.set_yticklabels(["0", "1", "2", "10", "100"])
        ax.set_xlabel(xlab, labelpad=1.5)
        if j == 0:
            ax.set_ylabel(r"$\Delta\chi^2$  from best fit")
        ax.set_title(title, loc="left", fontweight="bold", pad=5)
        ax.text(*npos, note, transform=ax.transAxes,
                ha="right" if npos[0] > 0.5 else "left", va="top",
                fontsize=6.5, color=C_BB, linespacing=1.35)
        gx, gha = (0.03, "left") if j == 0 else (0.97, "right")
        ax.text(gx, 0.045, r"$\Delta\chi^2 < 2$", transform=ax.transAxes,
                ha=gha, va="bottom", fontsize=6.3, color="#15803d")
        for x, y in zip(v / 1e3, dc):
            if y > 2:
                ax.annotate(f"{y:.0f}" if y >= 10 else f"{y:.1f}", xy=(x, y),
                            xytext=(0, 5), textcoords="offset points",
                            ha="center", fontsize=6, color="#3f3f46")

    save(fig, "fig2_fitted_history")


# =========================================================================
# FIGURE 3 -- the barrier in the joint SFS
# =========================================================================
def figure3():
    stats = json.load(open(R / "sfs2d_karyotype.json"))
    fig, axes = plt.subplots(1, 2, figsize=(7.1, 3.5))

    for ax, (key, tag, label) in zip(axes, (
            ("body", "a", "inversion body  (60.54–79.50 Mb)"),
            ("control", "b", "collinear control  (10–30 Mb)"))):
        m = np.loadtxt(TMP / f"AA_BB.{key}.2dSFS").reshape(81, 81)
        # The two monomorphic corners hold ~99% of the mass and would flatten
        # every polymorphic cell; they say nothing about the barrier.
        v = m.copy()
        v[0, 0] = v[-1, -1] = np.nan
        with np.errstate(divide="ignore", invalid="ignore"):
            lv = np.log10(np.where(v > 0, v, np.nan))

        im = ax.imshow(lv, origin="lower", cmap="magma", aspect="equal",
                       vmin=-1, vmax=4.2, extent=(0, 1, 0, 1),
                       interpolation="nearest")
        ax.plot([0, 1], [0, 1], lw=0.6, ls=(0, (2, 2)), color="#e4e4e7",
                alpha=0.55)
        ax.set_xticks([0, 0.25, 0.5, 0.75, 1.0])
        ax.set_yticks([0, 0.25, 0.5, 0.75, 1.0])
        ax.set_xlabel("derived allele frequency in BB  (inverted)",
                      labelpad=1.5)
        if key == "body":
            ax.set_ylabel("derived allele frequency in AA  (ancestral)")
        s = stats[key]
        nf = s["nearfix_AAalt"] + s["nearfix_BBalt"]
        ax.set_title(f"{tag}   {label}", loc="left", fontweight="bold", pad=5)
        ax.text(0.035, 0.965,
                f"shared polymorphism   {100 * s['shared'] / s['variable']:.1f}%\n"
                f"near-fixed differences   {nf:,.0f}",
                transform=ax.transAxes, ha="left", va="top", fontsize=6.8,
                color="white", linespacing=1.45,
                bbox=dict(fc="#18181b", ec="none", alpha=0.86, pad=3.2))
        for side in ("bottom", "left"):
            ax.spines[side].set_visible(False)

    cb = fig.colorbar(im, ax=axes, fraction=0.030, pad=0.020)
    cb.set_label("sites per cell  ($\\log_{10}$)", fontsize=7)
    cb.ax.tick_params(labelsize=6.5)
    cb.outline.set_visible(False)
    fig.suptitle("The recombination barrier is visible directly in the "
                 "joint SFS", x=0.062, y=1.005, ha="left", fontsize=8.5,
                 fontweight="bold")
    save(fig, "fig3_joint_sfs")


def main() -> None:
    print("building manuscript figures ->", OUT)
    figure1()
    figure2()
    figure3()
    print("done")


if __name__ == "__main__":
    main()
